services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: kotlin2025
      MYSQL_DATABASE: project_tool
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_tool?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kotlin2025

volumes:
  mysql_data:
